FSAssignment 04 WebTech/A1Patients/Controllers/FSMedicationTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using A1Patients.Models;

namespace A1Patients.Controllers
{
    public class FSMedicationTypesController : Controller
    {
        private readonly PatientsContext _context;

        public FSMedicationTypesController(PatientsContext context)
        {
            _context = context;
        }

        // GET: FSMedicationTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.MedicationType.ToListAsync());
        }

        // GET: FSMedicationTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medicationType = await _context.MedicationType
                .FirstOrDefaultAsync(m => m.MedicationTypeId == id);
            if (medicationType == null)
            {
                return NotFound();
            }

            return View(medicationType);
        }

        // GET: FSMedicationTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FSMedicationTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MedicationTypeId,Name")] MedicationType medicationType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(medicationType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(medicationType);
        }

        // GET: FSMedicationTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medicationType = await _context.MedicationType.FindAsync(id);
            if (medicationType == null)
            {
                return NotFound();
            }
            return View(medicationType);
        }

        // POST: FSMedicationTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MedicationTypeId,Name")] MedicationType medicationType)
        {
            if (id != medicationType.MedicationTypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medicationType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicationTypeExists(medicationType.MedicationTypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(medicationType);
        }

        // GET: FSMedicationTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medicationType = await _context.MedicationType
                .FirstOrDefaultAsync(m => m.MedicationTypeId == id);
            if (medicationType == null)
            {
                return NotFound();
            }

            return View(medicationType);
        }

        // POST: FSMedicationTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var medicationType = await _context.MedicationType.FindAsync(id);
            _context.MedicationType.Remove(medicationType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MedicationTypeExists(int id)
        {
            return _context.MedicationType.Any(e => e.MedicationTypeId == id);
        }
    }
}

FSAssignment 04 WebTech/A1Patients/Controllers/FSMedicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using A1Patients.Models;

namespace A1Patients.Controllers
{
    public class FSMedicationsController : Controller
    {
        private readonly PatientsContext _context;

        public FSMedicationsController(PatientsContext context)
        {
            _context = context;
        }

        // GET: FSMedications
        public async Task<IActionResult> Index(int? id)
        {

            try
            {
                if (id == null)
                {
                    string cookieFromClient = Request.Cookies["IdMedication"];
                    if (string.IsNullOrEmpty(cookieFromClient))
                    {
                        throw new Exception();
                    }
                    id = Convert.ToInt32(cookieFromClient);                    
                }
                Response.Cookies.Append("IdMedication", id.ToString());
            }
            catch (Exception)
            {
                ModelState.AddModelError("Error", "Selecione um tipo de medicamento");

            }

            var patientsContext = _context.Medication.Include(m => m.ConcentrationCodeNavigation).Include(m => m.DispensingCodeNavigation).Include(m => m.MedicationType).Where(m => m.MedicationTypeId == id).OrderBy(n => n.Name).OrderBy(c => c.Concentration);
            var medicationTypes  = _context.MedicationType.Find(id);

            ViewBag.Type = medicationTypes;

            return View(await patientsContext.ToListAsync());
        }

        // GET: FSMedications/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medication = await _context.Medication
                .Include(m => m.ConcentrationCodeNavigation)
                .Include(m => m.DispensingCodeNavigation)
                .Include(m => m.MedicationType)
                .FirstOrDefaultAsync(m => m.Din == id);
            if (medication == null)
            {
                return NotFound();
            }

            return View(medication);
        }

        // GET: FSMedications/Create
        public IActionResult Create(int Id)
        {
            ViewData["ConcentrationCode"] = new SelectList(_context.ConcentrationUnit.OrderBy(c => c.ConcentrationCode), "ConcentrationCode", "ConcentrationCode") ;
            ViewData["DispensingCode"] = new SelectList(_context.DispensingUnit.OrderBy(o => o.DispensingCode), "DispensingCode", "DispensingCode");
            ViewData["MedicationTypeId"] = new SelectList(_context.MedicationType, "MedicationTypeId", "Name");
            var medType = _context.MedicationType.Find(Id);
            ViewBag.MedType = medType;
            return View();
        }

        // POST: FSMedications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Din,Name,Image,MedicationTypeId,DispensingCode,Concentration,ConcentrationCode")] Medication medication)
        {
            if (ModelState.IsValid)
            {
                _context.Add(medication);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ConcentrationCode"] = new SelectList(_context.ConcentrationUnit, "ConcentrationCode", "ConcentrationCode", medication.ConcentrationCode);
            ViewData["DispensingCode"] = new SelectList(_context.DispensingUnit, "DispensingCode", "DispensingCode", medication.DispensingCode);
            ViewData["MedicationTypeId"] = new SelectList(_context.MedicationType, "MedicationTypeId", "Name", medication.MedicationTypeId);
            return View(medication);
        }

        // GET: FSMedications/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medication = await _context.Medication.FindAsync(id);
            if (medication == null)
            {
                return NotFound();
            }
            ViewData["ConcentrationCode"] = new SelectList(_context.ConcentrationUnit.Where(x=>x.ConcentrationCode == medication.ConcentrationCode), "ConcentrationCode", "ConcentrationCode", medication.ConcentrationCode);
            ViewData["DispensingCode"] = new SelectList(_context.DispensingUnit, "DispensingCode", "DispensingCode", medication.DispensingCode);
            ViewData["MedicationTypeId"] = new SelectList(_context.MedicationType, "MedicationTypeId", "Name", medication.MedicationTypeId);
            return View(medication);
        }

        // POST: FSMedications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Din,Name,Image,MedicationTypeId,DispensingCode,Concentration,ConcentrationCode")] Medication medication)
        {
            if (id != medication.Din)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medication);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicationExists(medication.Din))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ConcentrationCode"] = new SelectList(_context.ConcentrationUnit, "ConcentrationCode", "ConcentrationCode", medication.ConcentrationCode);
            ViewData["DispensingCode"] = new SelectList(_context.DispensingUnit, "DispensingCode", "DispensingCode", medication.DispensingCode);
            ViewData["MedicationTypeId"] = new SelectList(_context.MedicationType, "MedicationTypeId", "Name", medication.MedicationTypeId);
            return View(medication);
        }

        // GET: FSMedications/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medication = await _context.Medication
                .Include(m => m.ConcentrationCodeNavigation)
                .Include(m => m.DispensingCodeNavigation)
                .Include(m => m.MedicationType)
                .FirstOrDefaultAsync(m => m.Din == id);
            if (medication == null)
            {
                return NotFound();
            }

            return View(medication);
        }

        // POST: FSMedications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var medication = await _context.Medication.FindAsync(id);
            _context.Medication.Remove(medication);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MedicationExists(string id)
        {
            return _context.Medication.Any(e => e.Din == id);
        }
    }
}

FSAssignment 04 WebTech/A1Patients/Views/FSMedications/Create.cshtml
@model A1Patients.Models.Medication

@{
    ViewData["Title"] =  " Add a Medication for " + ViewBag.MedType.Name;
}

<h1>Create</h1>

<h4>Medication</h4>



<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Din" class="control-label"></label>
                <input asp-for="Din" class="form-control"/>
                <span asp-validation-for="Din" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label hidden asp-for="MedicationTypeId" class="control-label"></label>
                <select hidden asp-for="MedicationTypeId" class ="form-control" asp-items="ViewBag.MedicationTypeId">                    
                </select>
            </div>
            <div class="form-group">
                <label asp-for="DispensingCode" class="control-label"></label>
                <select asp-for="DispensingCode" class ="form-control" asp-items="ViewBag.DispensingCode"></select>
            </div>
            <div class="form-group">
                <label asp-for="Concentration" class="control-label"></label>
                <input asp-for="Concentration" class="form-control" />
                <span asp-validation-for="Concentration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConcentrationCode" class="control-label"></label>
                <select asp-for="ConcentrationCode" class ="form-control" asp-items="ViewBag.ConcentrationCode"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FSAssignment 04 WebTech/A1Patients/Views/FSMedications/Delete.cshtml
@model A1Patients.Models.Medication

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Medication</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Concentration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Concentration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ConcentrationCodeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ConcentrationCodeNavigation.ConcentrationCode)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DispensingCodeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DispensingCodeNavigation.DispensingCode)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MedicationType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MedicationType.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Din" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FSAssignment 04 WebTech/A1Patients/Views/FSMedications/Details.cshtml
@model A1Patients.Models.Medication

@{
    ViewData["Title"] = "Details of Medication for " + ViewBag.MedType.Name;
}

<h1>Details</h1>

<div>
    <h4>Medication</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Din)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Din)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Concentration)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Concentration)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ConcentrationCodeNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ConcentrationCodeNavigation.ConcentrationCode)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DispensingCodeNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DispensingCodeNavigation.DispensingCode)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MedicationType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MedicationType.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Din">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FSAssignment 04 WebTech/A1Patients/Views/FSMedications/Edit.cshtml
@model A1Patients.Models.Medication

@{
    ViewData["Title"] = "Edit of Medication for " + ViewBag.MedType.Name;
}

<h1>Edit</h1>

<h4>Medication</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <label asp-for="Din" class="control-label"></label>
            <input asp-for="Din" class="form-control" readonly/>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MedicationTypeId" class="control-label"></label>
                <select asp-for="MedicationTypeId" class="form-control" asp-items="ViewBag.MedicationTypeId"></select>
                <span asp-validation-for="MedicationTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DispensingCode" class="control-label"></label>
                <select asp-for="DispensingCode" class="form-control" asp-items="ViewBag.DispensingCode"></select>
                <span asp-validation-for="DispensingCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Concentration" class="control-label"></label>
                <input asp-for="Concentration" class="form-control" />
                <span asp-validation-for="Concentration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConcentrationCode" class="control-label"></label>
                <select asp-for="ConcentrationCode" class="form-control" asp-items="ViewBag.ConcentrationCode"></select>
                <span asp-validation-for="ConcentrationCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FSAssignment 04 WebTech/A1Patients/Views/FSMedications/Index.cshtml
@model IEnumerable<A1Patients.Models.Medication>

@{
    ViewData["Title"] =  "List all Medication for " + ViewBag.Type.Name;
}


@if (!ViewData.ModelState.IsValid && ViewData.ModelState["Error"].Errors.Count > 0)
{
    <div class="alert alert-danger">
        <a asp-action="Index" asp-controller="FSMedicationTypes"><strong>Erro! - </strong>@ViewData.ModelState["Error"].Errors.First().ErrorMessage </a>
    </div>
}
else
{     
    <p>
        <a asp-action="Create" asp-route-id="@ViewBag.Type.MedicationTypeId">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Din)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Image)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Concentration)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ConcentrationCodeNavigation)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DispensingCodeNavigation)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MedicationType)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Din)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Image)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Concentration)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ConcentrationCodeNavigation.ConcentrationCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DispensingCodeNavigation.DispensingCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MedicationType.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Din">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Din">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Din">Delete</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
}